### ISSUE TITLE
Not obvious how to stub chained promises

### ISSUE THREAD

**Issue by kfatehi** [bendrucker/sinon-as-promised#1]
I have to chain a promise like this:   `Project.findOne({name: job.project}).populate('creator').exec(function (err, project) { ... })`

I wish the README showed how to stub this common pattern. Thanks!

**Comment by carpiediem** [comment]
This solution works if you're calling `populate()` once, but what is it possible to create a more flexible stub that will work if `populate()` is called twice, once, or not at all?

```
Project.findOne({name: job.project}).populate('creator').populate('somethingElse')
Project.findOne({name: job.project})
```

**Comment by bendrucker** [comment]
Locking since I'm not looking to host this discuss and notify everyone. If you're looking to mock an API that looks like the above, you probably need to return `this` from your mocks.
