### ISSUE TITLE
Karma plug-in

### ISSUE THREAD

**Issue by demisx** [bendrucker/sinon-as-promised#16]
I was hoping there would be a karma plugin for this library, but couldn't find it. Is it possible to use it with karma without explicitly requiring it in each file? Thank you.

**Comment by bendrucker** [comment]
As mentioned in #17, I'm not a fan of these plugins that just include a file and then create the sort of dependency edge cases you encountered there. 

You don't need to require it in each file though. You can have a test setup file that you include in `config.files` before your tests. Have that do stuff like register sinon-as-promised and any chai plugins you're using. That way you have total code-level control over that file, no repetition, and avoid plugins altogether.

**Comment by bendrucker** [comment]
Here's how you'd do that:

**karma.conf.js**
```js
{
  files: [
    'test/setup.js',
    'test/**/*.js'
  ]
}
```

**setup.js**
```js
require('chai').use(require('chai-as-promised')).use(require('sinon-chai'));
require('sinon-as-promised');
require('bluebird').longStackTraces();
```

The contents of your setup file will differ but the idea stays the same. You're just registering plugins.

If you wanted to avoid having to even require sinon and chai in your tests:

```js
global.sinon = require('sinon');
global.expect = require('chai').expect;
```

The sky's the limit.

**Comment by demisx** [comment]
:+1: Thank you. This approach is so much better!

**Comment by nottinhill** [comment]
I created the setup.js, put "require('sinon-as-promised') in it and linked it in my Karma Conf files section. Now I am seeing 

    Can't find variable: require

Any ideas?

**Comment by bendrucker** [comment]
Please don't dump questions in old issues.
