### ISSUE TITLE
Not picking up sinon from karma-chai-plugin

### ISSUE THREAD

**Issue by demisx** [bendrucker/sinon-as-promised#17]
I am currently using [karma-chai-plugins](https://www.npmjs.com/package/karma-chai-plugins) for the common chai plugins. Amongst those, is `sinon-chai` that auto includes `sinon`. However, I still need to require `sinon` explicityly in each test for `sinon-as-promissed` to work, i.e: 

```js
var sinon = require('sinon');
var sinonAsPromised = require('sinon-as-promised');
```
Any way to make it to pick up `sinon` already loaded from the `karma-chai-plugins`?

**Comment by bendrucker** [comment]
Pretty sure you can switch to `chai-sinon`, silly as that may sound. If I remember right that uses sinon and chai as peer deps which means sinon as promised will get the same sinon instance. Thought that sinon-chai uses them as direct deps which means when you `require('sinon')` you're actually not getting that sinon instance. 

In general steer clear of these sorts of karma plugins though. You need a plugin for something like mocha. But there's no point in a chai plugin when you can just `require` chai and do what you need.

**Comment by demisx** [comment]
Thank you for you advice, Ben. The reason I've started using those plugins, that they let me avoid writing the same require lines at the top of each test file, thus keeping tests shorter. Do you know if there is a way to do that in karma without using plugins? In order words, I want to be able to specify some global javascript that I need to run before each test. Thank you.

**Comment by bendrucker** [comment]
Will drop an example in #17
