### ISSUE TITLE
possible to use sinon-as-promised with AngularJS 1.2 $q?

### ISSUE THREAD

**Issue by jmcmichael** [bendrucker/sinon-as-promised#20]
It appears as if sinon-as-promised chokes when passed an ng v1.2 $q object, as it is expecting a v1.3 $q function. I am writing tests for a ng v1.2 app which uses several components that haven't been upgraded to v1.3.

I've been struggling for a couple hours to use v1.2 promises with sinon-as-promised, but haven't been successful. Is is possible to use sinon-as-promised with a ng v1.2 application?

**Comment by bendrucker** [comment]
It's possible, yes, and I'll add an example and some docs soon. The issue here is that Angular 1.2 only exposes a deferred API and that's considered an antipattern for promises except in rare cases.

Instead of passing `$q` directly to sinon-as-promised, pass `qCtor`:

```js
function qCtor (fn) {
  var deferred = $q.defer();
  var resolve = angular.bind(deferred, deferred.resolve);
  var reject = angular.bind(deferred, deferred.reject);
  var promise = deferred.promise;

  fn(resolve, reject);

  return promise;
}
```

**Comment by jmcmichael** [comment]
Excellent, thanks - sinon-as-promised is now working w/ v1.2 $q after applying the shim.

**Comment by bendrucker** [comment]
Cool. And as mentioned in the new docs, you can use `angular-q-constructor` rather than copying and pasting.
