### ISSUE TITLE
Release version bundles bluebird

### ISSUE THREAD

**Issue by brian-mann** [bendrucker/sinon-as-promised#21]
Why does the released version bundle Bluebird?  I'm looking for a browser version without Bluebird being packaged, since I already have that separately.

**Comment by bendrucker** [comment]
Because the released version is only intended for people not using npm/browserify and therefore has to bundle all its dependencies. There's no problem mixing multiple versions of Bluebird if that's your concern. Or are you worried about file size?

**Comment by brian-mann** [comment]
Definitely worried about file size.  Bluebird is 5k+ lines.

**Comment by bendrucker** [comment]
Fair enough. Doing native promises w/ a polyfill as the default in v3. Bundle size is 95% smaller :)
