### ISSUE TITLE
How to reset promise back to native?

### ISSUE THREAD

**Issue by demisx** [bendrucker/sinon-as-promised#24]
I am using Angular 1.4 with karma/mocha+chai (no browserify).  In some tests, I call `sinonAsPromised($q)` and `$rootScope.$digest()` to resolve as shown in the examples. However, when testing ui router states in isolation, I cannot call `$rootScope.$digest()` as it will try to init all parent states.  Thus, I need to switch back to the native promise instead of $q. How would I do that? Thanks.

**Comment by bendrucker** [comment]
You can put back [native-promise-only](https://github.com/getify/native-promise-only) by depending on it yourself and passing it in, but I'd recommend dealing with the problem directly.
