### ISSUE TITLE
Getting sinon-as-promised to play nice with karma

### ISSUE THREAD

**Issue by nottinhill** [bendrucker/sinon-as-promised#25]
I created the `setup.js`, put `require('sinon-as-promised')` in it and linked it in my karma.conf.js `files` section as described in #16. Now I am seeing

    Can't find variable: require

Any ideas?

**Comment by bendrucker** [comment]
Please post your whole karma config file. Happy to help but closing b/c it's definitely not a sinon-a-p issue.

**Comment by nottinhill** [comment]
https://gist.github.com/nottinhill/5d374ac43dff9bbeb6b3

**Comment by bendrucker** [comment]
You need to make sure the test setup file is run through browserify otherwise no luck. If you wanna be old school and just use script tags just go full Bower and use the UMD build.

**Comment by nottinhill** [comment]
Thanks Ben! The old-school-way worked so far, now I am running the stubbed example (as coffeescript):

    it 'should throw and and catch an error', ->

      stub = sinonAsPromised.stub()
      stub.resolves('foo')

      stub().then((value) ->
        value == 'foo'
      )

      stub.onCall(0).resolves('bar')
      stub().then((value) ->
        value == 'bar'
      )

Unfortunately I am getting a 

	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

now.

**Comment by bendrucker** [comment]
You're not using it right, check the docs. You call `stub` on `sinon`, not `sinonAsPromised`.

**Comment by nottinhill** [comment]
Worked. Tnx.
