### ISSUE TITLE
Doesnt work with Q promises

### ISSUE THREAD

**Issue by antoaravinth** [bendrucker/sinon-as-promised#26]
I have a method which uses Q promises, like:

```
function testFn()
{
. . . . . 
    promise = getPromise({}) // returns Q promise

   promise.then(function(data){
         console.log(data)
         otherFn();
   })

 . . . . .
}

function otherFn()
{
    console.log("Called")
}
```

I'm using karma for my test cases, so I used this version of sinon-as-promise (https://github.com/bendrucker/sinon-as-promised/blob/v3.0.1/release/sinon-as-promised.js). 

My test case looks like this:

```
spyCalledFn = sandbox.spy(window,"otherFn");
var sinon = window.sinonAsPromised(Q.Promise)
var stub = sinon.stub(window,"getPromise"); 
stub.resolves('foo')

testFn()

assert.equal(spyCalledFn.calledOnce,true)
```

when the `testFn` is called, the following get printed:

```
foo

Called // <---- otherFn is called
```

However the `Called` statement gets printed, the assertion on the line:

```
assert.equal(spyCalledFn.calledOnce,true)
```

fails. I tried `callCount` method too, it says `0`. But  the console is printing its get called, not really sure whats going wrong here. Why Sinon couldn't able to spy this function?

Where I'm making mistake?

**Comment by bendrucker** [comment]
Promises resolve asynchronously and you're not waiting for it to resolve before you make your assertion. `testFn` needs to return a promise. And you need to do `testFn().then(makeAssertions)`.
