### ISSUE TITLE
Assertions not evaluated inside a then

### ISSUE THREAD

**Issue by pauleveritt** [bendrucker/sinon-as-promised#27]
As background, I try to write Angular applications as ES6 Node applications. My controllers and services are classes which have no Angular in them. I then write Mocha tests which are run in Mocha directly, without Karma.

I have a controller with a method which calls a method on a service:

```javascript
   getLogs(category, level) {
        return this.logs.getLogs(category, level)
            .then(
            (response) => {
                console.log(333, response);
                this.logs = response;
            },
            (error) => {
                console.log("ERRRRRR");
            }
        )
    }
```

(Note the console.log which I'llm mention in a moment.) I mock the service's getLog method, so I won't put in the implementation here. I have a test:

```javascript
import { expect } from "chai";
import sinon from "sinon";
import SinonAsPromised from "sinon-as-promised";

function $q(resolve, reject) {
    return new Promise(resolve, reject);
}

import Controller from "../logs.controller";

describe("Logs Controller methods", () => {

    var sandbox, logs, ctrl;

    beforeEach(() => {
        sandbox = sinon.sandbox.create();
        logs = {};
        ctrl = new Controller(logs);
    });

    afterEach(() => {
        sandbox.restore();
    });

    it("can call log data with success", () => {
        logs.getLogs = sinon.stub().resolves(3);
        ctrl.getLogs("category1", "level1")
            .then(() => {
                      console.log("Made it here");
                      expect(1).to.be(2);
                  });
    });
});
```

The "expect(1).to.be(2)" never gets evaluated with a failure. But the console.log above it does log. And the controller's console.log inside it's .then() does log, with the "3" that I resolved the stub with.

Any idea why the expect(1).to.be(2) doesn't fail?

**Comment by bendrucker** [comment]
Sorry, no immediate ideas other than that it may have something to do w/ the need to call `$timeout.flush` to trigger promise resolution in Angular. If you can provide a much lighter reproduction that indicates that this is a sinon-as-promised bug, happy to take another look!

**Comment by pauleveritt** [comment]
Here's a full gist: https://gist.github.com/pauleveritt/59bee84a5425bcb96d63

It includes both the controller being tested and the test. As shown, there's no Angular imported or included in any way. The $q that is passed in is a wrapper around an ES6 Promise instance (line 8).

It seems like I need some way to trigger the promise that is being mocked (the "logs.getLogs" method on the service.)

**Comment by pauleveritt** [comment]
Just to be clear, both console statements are called. It's weird that the one on line 52 is called, but the expect on the next line doesn't get evaluated. I'm running this under straight mocha, no karma.

**Comment by bendrucker** [comment]
Ok. As mentioned, I need a lighter example that I can run in Node. No dependencies but sinon-as-promised please. And in ES5 so I can run it.

**Comment by pauleveritt** [comment]
Here's a repo with a writeup and smallest-possible working example of the problem:

https://github.com/pauleveritt/sap-then-assert

No ES6, no Angular. Just run ``npm run test`` to see the issue.

**Comment by pauleveritt** [comment]
As further detail, walking through this in the debugger indicates that the assertion is running, and is failing, but isn't making it back out to the test reporter.

**Comment by bendrucker** [comment]
Much appreciated. Was able to very quickly identify the issue (you're using Mocha incorrectly and not telling it about the rejection):

https://github.com/bendrucker/sap-then-assert/commit/37dc66f04301e141141c6819324ad79edd917f18

**Comment by pauleveritt** [comment]
Ah, got it, very sorry about that. I thought it would be some boneheaded thing like that.

I have an example of writing promise-oriented controller/services/tests in this style, showing all the variations of resolve/reject, then/catch, etc. It’s a different flavor than your 3 existing examples. I’d like to make a documentation contribution to say thanks…would you prefer I put it in this repo and you link to it, or fork your repo and make a PR with another example?

—Paul

**Comment by bendrucker** [comment]
PRs are welcome for sure
