### ISSUE TITLE
Support notify event

### ISSUE THREAD

**Issue by evanliomain** [bendrucker/sinon-as-promised#31]
The notify event is not support. 

It could be nice, like `sinon.resolves()` and `sinon.rejects()`, to have a method like `sinon.notifies()` to notify the progression of the promise and call the notify callback.

**Comment by bendrucker** [comment]
Since it's not a standard feature (nor one I've ever used) this is non-trivial to implement. I'd be happy to review a PR but otherwise can't work on including it.
