### ISSUE TITLE
problem with sinon fakeTimers

### ISSUE THREAD

**Issue by killmenot** [bendrucker/sinon-as-promised#39]
Hi,

I'd like to use sinon fakeTimers and sinon-as-promised in my code but got wrong behaviour

Initial sample without sinon-as-promised from:
https://github.com/sinonjs/sinon/issues/738#issuecomment-129460050

```js
describe('sinon.useFakeTimers()', function() {
  before(function() {
    this.clock = sinon.useFakeTimers();
  });

  after(function() {
    this.clock.restore();
  });

  it('should resolve a promise after ticking', function() {
    var promise = new Promise(function( resolve ) {
      console.log(1);
      resolve();
    });

    this.clock.tick( 1000 );
    console.log(2)
  });
});
```

Output:
1
2

sinon-as-promised sample:
```js
var chai = require('chai');
var expect = chai.expect;
var sinon = require('sinon');
var sinonChai = require('sinon-chai');

chai.use(sinonChai);
require('sinon-as-promised');

describe.only('sample', function () {
  before(function() {
    this.clock = sinon.useFakeTimers();
  });

  after(function() {
    this.clock.restore();
  });

  it('should resolve a promise after ticking', function() {
    var callback = sinon.stub().resolves('test');
    
    callback().then(function () {
      console.log(1);
    });

    this.clock.tick(1000);
    console.log(2);
  });
});
```
Output
2
1

Do you have any idea why it works wrong?

**Comment by bendrucker** [comment]
Your examples are not equivalent. The resolver callback passed to `Promise` is called synchronously while all callbacks passed to `then` are called asynchronously.

**Comment by killmenot** [comment]
@bendrucker Yep, seems you're correct, I rewrote the first sample to make it works the same way like the second sample does. So, the problem is not in sinon-as-promised :)
