### ISSUE TITLE
Webpack Help

### ISSUE THREAD

**Issue by trainerbill** [bendrucker/sinon-as-promised#40]
Using webpack/karma/sinon/chai.  I can't require sinon-as-promised in the test or in a setup file like:

https://github.com/bendrucker/sinon-as-promised/issues/16

Getting 230:25-32 require function is used in a way in which dependencies cannot be statically extracted.  

I know this is a webpack/sinon issue but sinon and sinon-chai seem to work with the karma plugins.  Anyone know a way around this issue with sinon-as-promised or can a karma plugin be created?

**Comment by bendrucker** [comment]
See https://github.com/webpack/webpack/issues/304, this is unrelated to sinon-as-promised. I don't use Webpack but that's what came up when Googling.

**Comment by bendrucker** [comment]
> I know this is a webpack/sinon issue but sinon and sinon-chai seem to work with the karma plugins

That basically just means that they work when you don't use a module system and just insert globals. You're welcome to compile a version of sinon-as-promised that uses `window.sinon` instead of expecting is a module but I'm not going to publish that as part of the package.

**Comment by trainerbill** [comment]
If anyone finds this in the future, I had to upgrade to sinon 2.0.0-pre.  My working karma setup file:

```js
var chai = require('chai'),
  sinon = require('sinon'),
  sinonChai = require('sinon-chai'),
  promised = require('chai-as-promised');

sinon.behavior = require('sinon/lib/sinon/behavior');
sinon.defaultConfig = {
    injectInto: null,
    properties: ['spy', 'stub', 'mock', 'clock', 'server', 'requests'],
    useFakeTimers: true,
    useFakeServer: true
};

chai.use(promised);
chai.use(sinonChai);

require('sinon-as-promised');

global.expect = chai.expect;
global.should = chai.should();
global.sinon = sinon;


```
