### ISSUE TITLE
3.0.1 is listed as latest/default version

### ISSUE THREAD

**Issue by mjhm** [bendrucker/sinon-as-promised#42]
From https://www.npmjs.com/package/sinon-as-promised:
<img width="415" alt="screen shot 2016-07-24 at 8 23 26 am" src="https://cloud.githubusercontent.com/assets/431925/17084648/fdfa05a6-5177-11e6-8d7b-02e4f72b82cd.png">

**Comment by bendrucker** [comment]
Fixed
