### ISSUE TITLE
Webpack example

### ISSUE THREAD

**Issue by alexlukelevy** [bendrucker/sinon-as-promised#44]
Hi Ben,

I'm a big fan of the library but have struggling to use it with webpack and karma. Would it be possible to add an example configuration for webpack and karma? 

Simply adding karma-sinon-as-promised in the plugins and sinon-as-promised in the frameworks causes the following error: Uncaught ReferenceError: require is not defined.

So it looks like I need to tell webpack to make it ready for the browser before I use it, but I can't seem to find the correct solution for that. Importing it manually in test.js causes a different error: Unable to get property 'call' of undefined or null reference

Any ideas?

**Comment by bendrucker** [comment]
> Would it be possible to add an example configuration for webpack and karma?

No thanks, you're welcome to search through the issues or post something in this one for someone to discover in the future.

I try to avoid getting involved with people's build configuration for the sake of sanity. Any CommonJS bundler (browserify, webpack, etc.) will load the library normally, nothing special here.
