### ISSUE TITLE
sinon return promise

### ISSUE THREAD

**Issue by helderbrandao** [bendrucker/sinon-as-promised#48]
i want to pass in "resolves" instance a promise like this:
```javascript
sinon.stub().resolves(function() {
    return bluebird.resolve({"value": "foo"})
});
```

**Comment by bendrucker** [comment]
This library [returns thenables](https://github.com/bendrucker/sinon-as-promised/blob/master/index.js#L8-L10). Take advantage of thenables to get what you want here:

```js
sinon.stub().resolves({then: () => bluebird.resolve({value: 'foo'})})
```

Any A+ library will unwrap that when calling `then` on the outer promise.
