### ISSUE TITLE
Sinon as promised fails on Sinon 2.0.0+

### ISSUE THREAD

**Issue by ranhalprin** [bendrucker/sinon-as-promised#53]
sinon.behavior is no longer defined.

See https://github.com/sinonjs/sinon/blob/4cf4d58bd6feb1fd1ee72ab5226148c700af5cb5/docs/_releases/v2.0.0/migrating-to-2.0.md

**Comment by bendrucker** [comment]
https://github.com/bendrucker/sinon-as-promised/commit/55ffebb7966cffaa88602c46f8bbb491957a367f

**Comment by mbroadst** [comment]
I'm actually using this package with sinon v2 with no issues, so that peer dependency is pretty annoying 😄

**Comment by bendrucker** [comment]
Since sinon 2 adds promise support I will not consider changing the peer dep. This package supports sinon@1 although of course users are welcome to ignore the warnings and use at their own risk.
