### ISSUE TITLE
 Cannot set property 'resolves' of undefined when SAP module is compiled

### ISSUE THREAD

**Issue by jcollum-cambia** [bendrucker/sinon-as-promised#55]
Test code: 

```
const Lab = require('lab');
const lab = exports.lab = Lab.script();
const sinon = require('sinon');
require('sinon-as-promised');

describe('Events', () => {
  it('returns true when 1 + 1 equals 2', (done) => {
    lab.expect(1 + 1).to.equal(2);
    done();
  });
}); 
 ```

Failure: 

```
$ ./node_modules/.bin/lab -Rv  -e DEV  -r console ./test/unit -g "Processor"
C:\projects\constraint-listener\node_modules\sinon-as-promised\index.js:14
sinon.behavior.resolves = resolves
                        ^
TypeError: Cannot set property 'resolves' of undefined
    at Object.<anonymous> (C:\projects\constraint-listener\node_modules\sinon-as-promised\index.js:14:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Package.json: 

```
"devDependencies": {
  "aws-sdk-mock": "~1.7.0",
  "sinon": "~2.3.6",
  "sinon-as-promised": "~4.0.3",
  "eslint": "^4.1.1",
  "lab": "^14.1.0",
  "nodemon": "~1.11.0",
  "shortid": "^2.2.8"
},
```

Running on WIndows 10. 

```
$ node --version
v6.11.0
```

I'm working on isolating whether this is a windows issue or also happens on a mac

**Comment by bendrucker** [comment]
Not compatible with sinon 2, it comes with this behavior natively

**Comment by jcollum-cambia** [comment]
Crud, right there in the readme, sorry.

**Comment by naved1234** [comment]
I am facing the same issue as @jcollum-cambia 
here is my package.json file devDependencies,
`"devDependencies": {
    "chai": "^4.1.2",
    "chai-http": "^4.0.0",
    "eslint": "^4.19.1",
    "eslint-config-strongloop": "^2.1.0",
    "eslint-plugin-async-await": "0.0.0",
    "eslint-plugin-node": "^5.2.1",
    "mocha": "^5.1.1",
    "node-mocks-http": "^1.6.6",
    "nodemon": "^1.17.4",
    "nyc": "^11.7.2",
    "pre-commit": "^1.2.2",
    "proxyquire": "^2.0.1",
    "should": "^11.2.1",
    "sinon": "^7.1.1",
    "sinon-as-promised": "^4.0.3",
    "sinon-mongoose": "^2.2.1",
    "supertest": "^3.0.0"
  }`
