### ISSUE TITLE
Peer dependency Sinon is not provided

### ISSUE THREAD

**Issue by jmdeepak007git** [bendrucker/sinon-as-promised#72]
Hi Guys,

I am facing a warning issue as below:
markdown-spellcheck@npm:1.3.1 doesn't provide sinon (p2d3db), requested by sinon-as-promised.

It cant be fixed even after adding "sinon": "1 || 2" in the peerDependencies section. Could someone please advice and provide a fix. Thanks alot.

**Comment by bendrucker** [comment]
Read the docs please, the peer dependency is correct as is

**Comment by jmdeepak007git** [comment]
@bendrucker Could you please point me to the document ? Thanks alot.
