### ISSUE TITLE
create-thenable dependency change required 

### ISSUE THREAD

**Issue by OAFCROB** [bendrucker/sinon-as-promised#73]
### Issue

Receiving a deprecation warning for the third-party dependency `create-thenable` which has a usage of `main` in the package.json. Once the underlying package issue has been resolved, [see](https://github.com/bendrucker/create-thenable/blob/v1.0.2/package.json#L3C1-L3C19) and the new version has been tagged up. This package.json will need to be updated as well. 

This has been raised as an issue with `create-thenable`, [see](https://github.com/bendrucker/create-thenable/issues/3).

```
(node:59615) [DEP0128] DeprecationWarning: Invalid ‘main’ field in ‘/node_modules/create-thenable/package.json’ of ‘./src’. Please either fix that or report it to the module author
```

**Comment by bendrucker** [comment]
Patched, I'm going to skip bumping this:

https://github.com/bendrucker/sinon-as-promised/blob/master/package.json#L25

This package is not actively maintained and users can `npm update` to get the patched dependency.
